"""Sealed-source, bounded prefix audit; standard library only, no actor/Isaac.

Reads capture, policy, native streams only through first P06; records compact
actual measurements and selected native receipts. Never modifies source data.
This revised v2 draft has not been executed. The preserved non-v2 JSON/Markdown
were generated by the earlier script; use the verified summary for its
post-observation nominal timing clarification. Do not run alongside live Isaac.
"""
from pathlib import Path
import json
import math

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent
SOURCES = {
    'CP220544_v2': ROOT / 'runs/ppo_rr_capture_then_rl_transfer_v1/video_eval/validation/20260923T0356402230589Z_g26db2a1946e8_c1a7c95ca1db41d69882389e1e97cd8d/source',
    'CP221184_v4': ROOT / 'runs/ppo_rr_capture_then_rl_transfer_v1/video_eval/validation/20260923T0546444511040Z_g632295bc49cf_9a60bc74b9b14f6eb7debd0d2e92d914/source',
}
JOINTS = ('front_left_hip','front_left_knee','front_right_hip','front_right_knee',
          'rear_left_hip','rear_left_knee','rear_right_hip','rear_right_knee')
WHEELS = ('front_left_ankle','front_right_ankle','rear_left_ankle','rear_right_ankle')


def rows(path):
    with path.open(encoding='utf-8') as stream:
        for line in stream:
            if line.strip():
                yield json.loads(line)


def select(data, keys):
    return {key:data.get(key) for key in keys}


def compact(row):
    leg = row['current_legs']['FL']
    role = row['transfer_roles']['FL']['crossing_and_placement_evidence']
    return dict(tick=row['episode_physics_tick'], time=row['sim_time_s'], phase=row['phase'],
        FL=select(leg, ('air','ground_contact','top_contact','obstacle_pair_active','contact_surface',
            'bearing_force_n','load_fraction','initial_clearance','soft_air_actuation_earned',
            'front_distance_m','clearance_m','within_top_xy','consecutive_air_samples','consecutive_top_samples')),
        FL_history=role, placed=row['placed_history'],
        next_frame_nominal=row['nominal_full12'], final=row['dispatch']['drive_target_full12'],
        q=[row['joints'][name]['position_deg'] for name in JOINTS],
        wheel_velocity=[row['wheels'][name]['velocity_rad_s'] for name in WHEELS],
        FL_center=row['wheels'][WHEELS[0]]['center_w_m'],
        body_position=row['body']['position_w_m'], body_quaternion=row['body']['orientation_wxyz'],
        com=row['center_of_mass']['position_w_m'],
        FL_assist=select(row['capture_assist'], ('mode_name','reason','hip_target_deg','knee_hold_deg')),
        pending=select(row['capture_continuation'], ('fl_capture_pending','allow_capture_continuation','legal_capture_path')),
        RR_assist_mode=row['rr_capture_assist']['mode_name'], rr_task=row['rr_capture_transfer_context'])


def read_source(name, source):
    manifest = json.loads((source/'semantic_video_source_manifest.json').read_text(encoding='utf-8'))
    viewport = json.loads((source/'viewport_buffer_video_manifest.json').read_text(encoding='utf-8'))
    assert viewport['encoder_finalized_before_app_close'] and viewport['full_decode']['full_decode']
    assert manifest['fresh_process_single_episode'] and manifest['optimizer_updates'] == 0
    cp = manifest['checkpoint_load_provenance']
    assert cp['official_load_semantic_checkpoint'] and cp['policy_sampling_mode'] == 'deterministic_conditional_mean'
    summary = dict(source=str(source), checkpoint=cp['source'], runtime=manifest['runtime_contract']['source_git_commit'],
        saved_decisions=cp['saved_global_policy_decisions'], parameter_hashes=cp['parameter_hashes'],
        physical_duration=manifest['physical_episode']['physical_task_duration_s'],
        physical_success=manifest['physical_task_success'], video_valid=viewport['valid'],
        video_decode_duration=viewport['full_decode']['duration_s'], video_sha=viewport['video_sha256'],
        source_acceptance_error=manifest['source_acceptance_error'],
        camera=manifest['camera'], seed=manifest['seed'], policy_contract=cp['policy_contract'],
        final_whole_source_placed=manifest['physical_episode']['physical_task_evaluation']['history']['placed'],
        selected_configuration=manifest['runtime_contract']['selected_configuration'],
        pre_limit_reset_state_hash=manifest['natural_reset_proof']['reset_metadata']['phase_snapshot_restoration']['reset_only_state_writes']['pre_limit_native_state_observed_sha256'],
        front_control_files={path:value for path,value in manifest['runtime_contract']['files'].items()
            if path in ('src/wlr50_clean/ppo/semantic_capture_assist.py',
                        'src/wlr50_clean/ppo/semantic_nominal_geometry.py',
                        'src/wlr50_clean/ppo/semantic_transfer_roles.py',
                        'configs/recording_motion_contract.json')})
    captures, events, starts = {}, [], {}
    previous = None
    masks, rr_modes, rr_guidance = set(), set(), set()
    for row in rows(source/'capture_assist_ticks.jsonl'):
        value = compact(row)
        tick, phase = value['tick'], value['phase']
        captures[tick] = value
        if phase not in starts:
            starts[phase] = {'tick':tick, 'time':value['time']}
            events.append({'kind':'stage_start', 'phase':phase, 'tick':tick, 'time':value['time']})
        masks.add(tuple(row['policy_permission_mask_full12']))
        rr_modes.add(value['RR_assist_mode'])
        rr_guidance.add(value['rr_task']['fl_wheel_guidance_active'])
        if previous:
            for group, keys in (('FL', ('air','ground_contact','top_contact','initial_clearance','soft_air_actuation_earned')),
                                ('FL_history', ('active_lift','front_edge_crossed','placed'))):
                for key in keys:
                    a, b = previous[group][key], value[group][key]
                    if a != b and (int(phase[1:]) >= 4 or key == 'active_lift'):
                        events.append({'kind':group+'.'+key, 'before':a, 'after':b,
                                       'tick':tick, 'time':value['time'], 'phase':phase})
        previous = value
        if phase == 'P06':
            break
    summary.update(stage_starts=starts, events=events, mask_values=[list(x) for x in sorted(masks)],
        RR_modes_before_P06=sorted(rr_modes), RR_guidance_before_P06=sorted(rr_guidance),
        analyzed_last_tick=max(captures), capture_rows=len(captures))
    decisions = {}
    last = None
    for row in rows(source/'video_policy_decisions.jsonl'):
        info, policy = row['step_info'], row['policy_request']
        task = info['semantic_task']
        key = row['end_tick']
        decisions[key] = dict(decision=row['decision'], start_tick=row['start_tick'], end_tick=key,
            phase=row['request_phase'], end_phase=info['end_phase_id'],
            raw=row['raw_policy_action_full12'], base_mean=policy['base_mean_full12'],
            conditional_mean=policy['conditional_mean_full12'],
            previous_request=policy['previous_filtered_request_full12'],
            history_center=policy['history_center_full12'],
            rr_assist_observed=policy['rr_capture_assist_observed_features'],
            rr_task_observed=policy['rr_capture_transfer_observed_features'],
            termination_reason=info['termination_reason'], termination_source=task['termination_source'],
            stage_age=task['stage_age_s'], completion_values=task['completion_values'],
            local_timeout=task['local_timeout'])
        last = decisions[key]
        if int(info['end_phase_id'][1:]) >= 6:
            break
    summary['last_analyzed_decision'] = last
    return summary, captures, decisions


def first_difference(a, b, field, tolerance=1e-9):
    for tick in sorted(set(a)&set(b)):
        left, right = a[tick][field], b[tick][field]
        if len(left) != len(right):
            raise ValueError('field dimension mismatch')
        delta = [y-x for x,y in zip(left,right)]
        if any(abs(x)>tolerance for x in delta):
            return {'tick':tick, 'time':tick/120., 'tolerance':tolerance,
                'old_phase':a[tick]['phase'], 'new_phase':b[tick]['phase'],
                'old':left, 'new':right, 'new_minus_old':delta}
    return None


def native_selected(source, ticks, end_tick):
    found = {}
    sources = {}
    active_wheel_projection = 0
    mask_values, all_verified = set(), True
    for row in rows(source/'native_tick_audit.jsonl'):
        tick = row['episode_physics_tick']
        if tick > end_tick:
            break
        n = row['native_audit']
        sources[tick] = {'phase':row['source_phase_id'], 'source_N':row['nominal_full12']}
        mask_values.add(tuple(n['phase_mask_full12']))
        all_verified &= n['verified'] is True and n['setter_dispatch_targets_equal'] is True
        wheel = n.get('rr_carry_wheel_evidence')
        if wheel and any(abs(x)>1e-12 for x in wheel.get('controller_delta_full12', [])):
            active_wheel_projection += 1
        if tick in ticks:
            found[tick] = dict(source_N=row['nominal_full12'],
                raw=n['raw_policy_action_full12'], residual_permission_mask=n['phase_mask_full12'],
                filtered_request=row['projected_residual_full12'],
                mapped_native_N=n['native_drive_target_full12'],
                effective_policy_residual=n['policy_headroom_evidence']['effective_policy_residual_full12'],
                native_targets=n['actual_native_targets'], zero_current_policy_native=n['counterfactual_native_targets'],
                controller_bias=n['controller_drive_bias_full12'],
                rr_wheel_evidence=wheel,
                FL_assist_owner=n.get('capture_assist_owned_channels_full12'),
                RR_assist_owner=n.get('rr_capture_assist_owned_channels_full12'))
    return found, sources, dict(all_native_verified=all_verified, masks=[list(x) for x in sorted(mask_values)],
                       rr_wheel_projection_nonzero_rows=active_wheel_projection)


def main():
    target = OUT/'CP221184_vs_CP220544_front_divergence_v2.json'
    report = target.with_suffix('.md')
    if target.exists() or report.exists():
        raise RuntimeError('refuse to overwrite evidence')
    summaries, captures, decisions = {}, {}, {}
    for name, source in SOURCES.items():
        summaries[name], captures[name], decisions[name] = read_source(name,source)
    old, new = tuple(SOURCES)
    differences = {field:first_difference(captures[old],captures[new],field,tol)
        for field,tol in (('next_frame_nominal',1e-9),('final',1e-9),('q',1e-6),('wheel_velocity',1e-6),('body_position',1e-8))}
    differences['raw_policy'] = first_difference(decisions[old],decisions[new],'raw',1e-9)
    selected = {1,8,120,240,1200,2400,3600,4800,6000,7200}
    for name, summary in summaries.items():
        selected.add(summary['analyzed_last_tick'])
        for event in summary['events']:
            if event['kind'] == 'stage_start' or event['kind'] in ('FL_history.active_lift','FL_history.front_edge_crossed','FL_history.placed'):
                selected.update((event['tick']-1,event['tick'],event['tick']+1))
        # First actual loss of continuous AIR can precede ground revocation.
        first_air_loss = next((e for e in summary['events'] if e['kind']=='FL.air'
            and e['before'] is True and e['after'] is False
            and captures[name][e['tick']]['FL_history']['active_lift']), None)
        if first_air_loss:
            tick=first_air_loss['tick']
            summary['first_AIR_loss_after_FL_qualification']=captures[name][tick]
            selected.update((tick-1,tick,tick+1))
        p05_rows=[r for r in captures[name].values() if r['phase']=='P05']
        if p05_rows:
            peak=max(p05_rows,key=lambda r:abs(r['q'][2]-r['final'][2]))
            summary['P05_peak_FR_hip_target_tracking_error']={
                'tick':peak['tick'],'time':peak['time'],'target':peak['final'][2],
                'actual':peak['q'][2],'actual_minus_target':peak['q'][2]-peak['final'][2]}
            selected.add(peak['tick'])
        # Exact first ground-after-earned-current-lift, not initial ground at reset.
        earned=False
        for tick, row in captures[name].items():
            earned |= row['FL_history']['active_lift']
            if earned and row['FL']['ground_contact']:
                summary['first_ground_after_FL_qualification'] = row
                selected.update((tick-1,tick,tick+1))
                break
    for diff in differences.values():
        if diff: selected.update((diff['tick'],diff['tick']+1))
    # Phase-relative entry alignment is diagnostic, not identical actor input.
    for name, summary in summaries.items():
        start=summary['stage_starts']['P05']['tick']
        selected.update(start+offset for offset in (0,80,600,1080,1200))
    result = {'schema':'sealed_front_divergence_readonly.v1',
        'units':{'q':'canonical degrees','wheel':'canonical rad/s','distance':'world meters'},
        'ordering':{'joints':JOINTS,'wheels':WHEELS},
        'learning_between_candidates':{'policy_decisions':640,'ppo_updates':5,'adam_steps':100,
            'credited_phases':{'P07':3,'P08':2,'P09':635},'front_prefix_credit':False},
        'summaries':summaries,'first_same_tick_differences':differences,'selected':{},
        'supersedes':'CP221184_vs_CP220544_front_divergence.md/json: clarify next-frame nominal vs actual preceding-dispatch source and add first AIR loss',
        'configuration_comparison':{
            'camera_same':summaries[old]['camera']==summaries[new]['camera'],
            'policy_contract_same':summaries[old]['policy_contract']==summaries[new]['policy_contract'],
            'pre_limit_reset_state_hash_same':summaries[old]['pre_limit_reset_state_hash']==summaries[new]['pre_limit_reset_state_hash'],
            'front_control_file_hashes_same':summaries[old]['front_control_files']==summaries[new]['front_control_files'],
            'selected_configuration_changed':[k for k,v in summaries[new]['selected_configuration'].items()
                if summaries[old]['selected_configuration'].get(k)!=v]},
        'causal_limit':'Different deterministic policies and evolving physical trajectories. Full actor input vectors were not persisted here; no same-input actor replay or matched-policy physical counterfactual was run.'}
    native_sources={}
    for name, source in SOURCES.items():
        native, native_sources[name], audit = native_selected(source,selected,summaries[name]['analyzed_last_tick'])
        summaries[name]['native_summary'] = audit
        result['selected'][name] = [{**captures[name][tick], 'native':native.get(tick),
            'decision':next((decisions[name][end] for end in (int(math.ceil(tick/8)*8),) if end in decisions[name]),None)}
            for tick in sorted(selected) if tick in captures[name]]
    differences['actual_before_dispatch_source_N']=first_difference(native_sources[old],native_sources[new],'source_N',1e-9)
    target.write_text(json.dumps(result,indent=2,allow_nan=False),encoding='utf-8')
    lines=['# Sealed front divergence: CP221184 v4 vs CP220544 v2','',
        'Read-only CPU audit; no actor forward, physics, optimization or source modifications. Streams stop at first P06; the current run ends in P05. Detailed selected per-channel native/target/actual evidence is in the adjacent JSON. This v2 clarifies that capture-row nominal describes the next frame; the same-action source comes from native-row nominal_full12. Earlier draft remains preserved, superseded.','',
        '| Candidate | Whole source duration | Prefix analysis last stage | Recorded local terminal |',
        '|---|---:|---|---|']
    for name,s in summaries.items():
        last=s['last_analyzed_decision']
        lines.append(f"| {name} | {s['physical_duration']:.6f}s | {last['end_phase']} | {last['termination_reason']} / {last['termination_source']} |")
    lines += ['','## Stage entry samples','', '| Candidate | Stage | Tick | Time(s) |','|---|---|---:|---:|']
    for name,s in summaries.items():
        for phase,row in s['stage_starts'].items():
            lines.append(f"| {name} | {phase} | {row['tick']} | {row['time']:.6f} |")
    lines += ['','## FL earned qualification and first ground recontact','']
    for name,s in summaries.items():
        lines.append(f'### {name}')
        for e in s['events']:
            if e['kind'].startswith('FL_history.'):
                lines.append(f"- {e['kind']}: {e['before']} -> {e['after']} at tick {e['tick']} / {e['time']:.6f}s / {e['phase']}")
        g=s.get('first_ground_after_FL_qualification')
        if g:
            lines.append(f"- First ground after earned lift: tick {g['tick']} / {g['time']:.6f}s; front {g['FL']['front_distance_m']*1000:.3f} mm; gap {g['FL']['clearance_m']*1000:.3f} mm; target FL hip/knee {g['final'][:2]}, actual {g['q'][:2]}; wheels target {g['final'][8:]}, actual {g['wheel_velocity']}.")
        else: lines.append('- No ground recontact after FL qualification in analyzed prefix.')
        air=s.get('first_AIR_loss_after_FL_qualification')
        if air:
            lines.append(f"- Earlier continuous-AIR loss: tick {air['tick']} / {air['time']:.6f}s; surface={air['FL']['contact_surface']}, ground={air['FL']['ground_contact']}, obstacle_pair={air['FL']['obstacle_pair_active']}, front={air['FL']['front_distance_m']*1000:.3f} mm, gap={air['FL']['clearance_m']*1000:.3f} mm; earned lift remains {air['FL_history']['active_lift']} here, distinct from later ground revocation.")
        peak=s.get('P05_peak_FR_hip_target_tracking_error')
        if peak: lines.append(f"- P05 peak FR hip actual-minus-FINAL: {peak['actual_minus_target']:.3f} deg at {peak['time']:.6f}s; target {peak['target']:.3f}, actual {peak['actual']:.3f}. Tracking/coupling diagnostic, not an actuator-fault or causal proof.")
        lines.append('')
    lines += ['## First recorded same-tick differences','']
    for field,d in differences.items():
        if d: lines.append(f"- {field}: tick {d['tick']} / {d['time']:.6f}s ({d['old_phase']} vs {d['new_phase']}); maximum absolute delta {max(abs(x) for x in d['new_minus_old']):.9g}.")
    lines += ['- raw_policy comparison above is labelled by the first decision end_tick=8; its same action is already physically applied at tick1.','',
        '## Current CP221184 exact FL-ground event: canonical four-wheel path','',
        '| Wheel | Actual source N | Effective policy residual | FINAL target | Measured angular velocity |',
        '|---|---:|---:|---:|---:|']
    ground=summaries[new].get('first_ground_after_FL_qualification')
    if ground:
        full=next(r for r in result['selected'][new] if r['tick']==ground['tick'])
        for i,leg in enumerate(('FL','FR','RL','RR')):
            n=full['native']
            lines.append(f"| {leg} | {n['source_N'][8+i]:.6f} | {n['effective_policy_residual'][8+i]:.6f} | {full['final'][8+i]:.6f} | {full['wheel_velocity'][i]:.6f} |")
    lines += ['','## Control identity and observed bypass','',
        json.dumps(result['configuration_comparison'],ensure_ascii=False),
        '- Both actual permission masks stayed all-ones; every inspected native dispatch verified. RR assist stayed WAIT; v4 wheel controller_delta was exactly zero throughout this failed front attempt. The new rear projection did not issue the front reversal.',
        '- 26db->632 task-spec diff only adds the RR-contact handoff opt-in. Profile diff only changes revision, RR feedback revision and RR wheel mode. Front reward/schema/source Recording and P05 capture-controller bytes are preserved. This is a scoped control comparison, not full runtime byte identity.']
    lines += ['','Both masks and native write verification are reported separately from residual/controller effects. Canonical wheel rotation is not wheel-end displacement or proof of traction. No historical placement is substituted for current contact.','',
        result['causal_limit'],'', '640 rear-only real decisions / 5 PPO updates / 100 Adam steps are preserved as learned lineage; excluded deterministic prefixes are not front rehearsal samples. No task success or stability-improvement claim.']
    report.write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(json.dumps({'report':str(report),'json':str(target),'selected_counts':{k:len(v) for k,v in result['selected'].items()},'first_differences':{k:None if v is None else v['tick'] for k,v in differences.items()}}))


if __name__ == '__main__':
    main()
